### ISSUE TITLE
$GIT_PYTHON_GIT_EXECUTABLE required

### ISSUE THREAD

**Issue by krcb197** [SystemRDL/PeakRDL-ipxact#13]
I am trying to compile a systemRDL file to the command line using the following versions:
* peakrdl 0.4.
* peakrdl-ipxact 3.3.0

I use the following command
```bash
peakrdl ip-xact tests\testcases\simple.rdl -o tests\testcases\simple.xmlpeakrdl
```

This results in the following errors:
```
Traceback (most recent call last):
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\git\cmd.py", line 306, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\<hidden>\Documents\GitHub\PeakRDL-python\venv\Scripts\peakrdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('peakrdl==0.4.0', 'console_scripts', 'peakrdl')())
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\peakrdl\main.py", line 42, in main
    subcommands += get_exporter_plugins()
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\peakrdl\plugins\exporter.py", line 87, in get_exporter_plugins
    exporter = ExporterSubcommandPluginWrapper(ep.name, ep.load())
  File "C:\Users\<hidden>\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\<hidden>\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\peakrdl_html\__init__.py", line 1, in <module>
    from .exporter import HTMLExporter
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\peakrdl_html\exporter.py", line 15, in <module>
    from gitmetheurl import GitMeTheURL
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\gitmetheurl\__init__.py", line 3, in <module>
    from .base import GitMeTheURL, GMTUException
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\gitmetheurl\base.py", line 5, in <module>
    import git
  File "c:\users\<hidden>\documents\github\peakrdl-python\venv\lib\site-packages\git\__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

Why does the export process need to access Git?

**Comment by amykyta3** [comment]
What version of peakrdl-html are you using? Try upgrading that to the
latest version. It should pull in the fix for this behavior.

**Comment by krcb197** [comment]
I have just updated to peakrdl-html version 2.9.0 from 2.7.0. That resolved the issue.
